---
# defaults file for ansible-tower-manage

############################################################
#               Tower Installation Vars                    #
############################################################

# Working location for installation files
tower_working_location: "/var/tmp"

# vars file for install_ocp
tower_ocp_releases_url: https://releases.ansible.com/ansible-tower/setup_openshift/
tower_ocp_setup_file: ansible-tower-openshift-setup-{{ tower_release_version }}.tar.gz

# Tower variables
tower_admin_user: "admin"
tower_admin_password: "password"

# Tower Install Verbosity
tower_verbose_install: false

# Tower secret key
tower_secret_key: "mysecret"

# Postgresql variables

# pg_hostname: pg.tower.example.com
tower_pg_database: "awx"
tower_pg_username: "awx"
tower_pg_password: "password"
tower_pg_port: 5432
tower_pg_sslmode: "prefer"

############################################################
#               Kubernetes vars.                 #
############################################################

# Deploy into Vanilla Kubernetes
# ==============================
# Tower can be deployed to a Kubernetes instance for testing purposes.
# A context should be set this is the equivalant of being logged in.
# A pull secret for registry.redhat.io is likely needed  if not already setup.
# Tower Install version Openshift/Kubernetes

kubernetes_context: minikube
kubernetes_namespace: default
kubernetes_image_pull_secrets: tower-mini-pull-secret
...
